name: On Merge

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}


on:
 push:
    branches:
       - 'main'

jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.3

    # - name: AWS credentials 
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with: 
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    #     aws-region:  us-east-1
    
    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Installing packer provisioners
      run: packer init ami.pkr.hcl


    - name: Printing the contents of Directory
      run: ls -l


    - name: Building Packer Template
      run: packer build ami.pkr.hcl

    - name: Printing the contents of Directory after building
      run: ls -l
